source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BigViewModel_Example' do
  pod 'BigViewModel', :path => '../'
  
  target 'BigViewModel_Tests' do
  pod 'BigViewModel', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end

end

