source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BigViewModel_Example', :exclusive => true do
  pod 'BigViewModel', :path => '../'
end

target 'BigViewModel_Tests', :exclusive => true do
  pod 'BigViewModel', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
